server:
port: 8080

spring:
web:
resources:
static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
# Database
datasource:
driver-class-name: org.postgresql.Driver
url: jdbc:postgresql://localhost:8080:5432/
username: superuser
password: postgresql
# jpa properties
jpa:
hibernate:
ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
show-sql: true
database: postgresql
database-platform: org.hibernate.dialect.PostgreSQLDialect
open-in-view: false
generate-ddl: true

# ??? ??? ??? ?? ???
defer-datasource-initialization: false

sql:
init:
platform: postgres
